version: "3.3"
services:
  build_env:
    build: "."
    image: "d2dcn_dwi"
    volumes:
      - ../:/home/docker/workspace
      - ../.ssh/:/home/docker/.ssh
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=:0
    stdin_open: true 
    tty: true
    network_mode: "bridge"
    privileged: true
